### ISSUE TITLE
Ruby code block highlighting seems mis-configured

### ISSUE THREAD

**Issue by hiattp** [Verumex/vmx_engineering#3]
Every time a class is defined it colors the remaining text blue for some reason 🤔 

<img width="786" alt="Screen Shot 2019-10-02 at 9 15 42 AM" src="https://user-images.githubusercontent.com/571459/66057088-583ca280-e4f5-11e9-9c8d-878448dc46a3.png">

@janklimo have you run into this before? I'm hoping you've used this highlighting library in one of your other gatsby projects 😁

https://prismjs.com

**Comment by janklimo** [comment]
It thinks it's JavaScript. I'm using Highlight.js on my blog but Prism looks cool too. I think it needs just a little bit more config.

**Comment by hiattp** [comment]
Ah...looks like the prism wrapper the gatsby starter used doesn't [actually support](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) ruby by default 🙄
